In [1]:
from alpha_vantage.timeseries import TimeSeries

API_KEY = 'OWIJ9Z9AIORO0H21'

ts = TimeSeries(key=API_KEY, output_format='pandas')

In [5]:
data = ts.get_monthly_adjusted('AAPL')
data[0]

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount
date,,,,,,,
2024-08-13,224.37,225.60,196.000,221.27,221.2700,5.923413e+08,0.25
2024-07-31,212.09,237.23,211.920,222.08,221.8251,1.153193e+09,0.00
2024-06-28,192.90,220.20,192.150,210.62,210.3782,1.723984e+09,0.00
2024-05-31,169.58,193.00,169.110,192.25,192.0293,1.336570e+09,0.25
2024-04-30,171.19,178.36,164.075,170.33,169.9024,1.240411e+09,0.00
...,...,...,...,...,...,...,...
2000-04-28,135.50,139.50,104.870,124.06,0.9353,7.734290e+07,0.00
2000-03-31,118.56,150.38,114.000,135.81,1.0239,7.766390e+07,0.00
2000-02-29,104.00,119.94,97.000,114.62,0.8642,6.535520e+07,0.00
2000-01-31,104.87,121.50,86.500,103.75,0.7822,1.120998e+08,0.00
1999-12-31,101.00,118.00,91.060,102.81,0.7751,8.409120e+07,0.00

In [8]:
from alpha_vantage.fundamentaldata import FundamentalData

Key = 'OWIJ9Z9AIORO0H21'

fd = FundamentalData(key=Key, output_format='pandas')

data, meta_data = fd.get_income_statement_annual('AAPL')
data.T

date,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000007,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000011,1970-01-01 00:00:00.000000012,1970-01-01 00:00:00.000000013,1970-01-01 00:00:00.000000014
fiscalDateEnding,2023-09-30,2022-09-30,2021-09-30,2020-09-30,2019-09-30,2018-09-30,2017-09-30,2016-09-30,2015-09-30,2014-09-30,2013-09-30,2012-09-30,2011-09-30,2010-09-30,2009-09-30
reportedCurrency,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD
grossProfit,169148000000,170782000000,152836000000,104956000000,98392000000,101839000000,88186000000,84263000000,93626000000,70537000000,64304000000,68662000000,43818000000,25684000000,17222000000
totalRevenue,379352000000,391397000000,363172000000,271642000000,256598000000,265595000000,229234000000,215639000000,232982000000,182411000000,170774000000,156508000000,108249000000,65225000000,42905000000
costOfRevenue,239069000000,248640000000,234954000000,189475000000,180027000000,163756000000,141048000000,131376000000,163618000000,131151000000,123236000000,100486000000,73630000000,45873000000,29832000000
costofGoodsAndServicesSold,214137000000,223546000000,212981000000,169559000000,161782000000,163756000000,141048000000,131376000000,140089000000,112258000000,106606000000,87846000000,64431000000,39541000000,25683000000
operatingIncome,114301000000,119437000000,108949000000,66288000000,63930000000,70898000000,61344000000,60024000000,71230000000,52503000000,48999000000,55241000000,33790000000,18385000000,11740000000
sellingGeneralAndAdministrative,24932000000,25094000000,21973000000,19916000000,18245000000,16705000000,15261000000,14194000000,14329000000,11993000000,10830000000,10040000000,7599000000,5517000000,4149000000
researchAndDevelopment,29915000000,26251000000,21914000000,18752000000,16217000000,14236000000,11581000000,10045000000,8067000000,6041000000,4475000000,3381000000,2429000000,1782000000,1333000000
operatingExpenses,54847000000,51345000000,43887000000,38668000000,34462000000,30941000000,26842000000,24239000000,22396000000,18034000000,15305000000,13421000000,10028000000,7299000000,5482000000
investmentIncomeNet,3750000000,2825000000,2843000000,3763000000,4961000000,5686000000,5201000000,3999000000,2921000000,1795000000,1616000000,1088000000,519000000,None,None
netInterestIncome,-3933000000,-2931000000,-2645000000,-2873000000,-3576000000,-3240000000,-2323000000,-1456000000,-733000000,-384000000,-136000000,0,0,None,None
interestIncome,183000000,106000000,2843000000,3763000000,4961000000,5686000000,5201000000,3999000000,None,None,None,None,None,None,None
interestExpense,3933000000,2931000000,2645000000,2873000000,3576000000,3240000000,2323000000,1456000000,733000000,384000000,136000000,0,0,155000000,326000000
nonInterestIncome,383285000000,394328000000,365817000000,274515000000,260174000000,265595000000,229234000000,None,None,None,None,None,None,None,None
otherNonOperatingIncome,-382000000,-228000000,60000000,-87000000,422000000,-441000000,-133000000,-1195000000,-903000000,-431000000,-324000000,-566000000,-104000000,155000000,326000000
depreciation,8500000000,8700000000,9500000000,9700000000,11300000000,9300000000,8200000000,8300000000,None,None,None,None,None,None,None
depreciationAndAmortization,11519000000,11104000000,11284000000,11056000000,12547000000,10903000000,1200000000,8300000000,9200000000,6900000000,5800000000,2600000000,1600000000,815000000,606000000
incomeBeforeTax,113736000000,119103000000,109207000000,67091000000,65737000000,72903000000,64089000000,61372000000,72515000000,53483000000,50155000000,55763000000,34205000000,18540000000,12066000000
incomeTaxExpense,16741000000,19300000000,14527000000,9680000000,10481000000,13372000000,15738000000,15685000000,19121000000,13973000000,13118000000,14030000000,8283000000,4527000000,3831000000
interestAndDebtExpense,3933000000,2931000000,2645000000,2873000000,3576000000,3240000000,2323000000,1456000000,733000000,384000000,136000000,0,0,None,None
netIncomeFromContinuingOperations,96995000000,99803000000,94680000000,57411000000,55256000000,59531000000,48351000000,45687000000,53394000000,39510000000,37037000000,41733000000,25922000000,14013000000,8235000000
comprehensiveIncomeNetOfTax,96652000000,88531000000,95249000000,57453000000,58037000000,56505000000,47567000000,46666000000,51967000000,41063000000,36067000000,41789000000,26411000000,13890000000,8321000000
ebit,117669000000,122034000000,111852000000,69964000000,69313000000,76143000000,66412000000,62828000000,73248000000,53867000000,50291000000,55763000000,34205000000,18385000000,11740000000
ebitda,125820000000,130541000000,120233000000,77344000000,76477000000,81801000000,67612000000,71128000000,82448000000,60767000000,56091000000,58363000000,35805000000,19200000000,12346000000
netIncome,96995000000,99803000000,94680000000,57411000000,55256000000,59531000000,48351000000,45687000000,53394000000,39510000000,37037000000,41733000000,25922000000,14013000000,8235000000